### ISSUE TITLE
Make DataConverter work on a Node.js environment (non browser environment)

### ISSUE THREAD

**Issue by danizep** [IFCjs/components#117]
### Description 📝

Our team, created a backend Node.js IFC converter inspired on OBC's `FragmentIfcLoader`.

At the time we were using OBC `1.0.0-alpha.64`. Since then 1.1.0 was released and we really wish to update to the latest version of OBC for the sake of being synced with the frontend.

When updating I noticed that, `DataConverter` now requires that a `Components` instance to be passed on the constructor.

As `Components` interact with web APIs like `document`, this doesn't really work on a Node.js environment.

We really wish that this could be improved to foster code reusability.

Thank you ;) 

### Suggested solution 💡

Make `Components` optional for `DataConverter`.

### Alternative ⛕

Validate the environment in which the code it's running and not make use of browser API's when not available.

### Validations ✅

- [X] Read the [docs](https://platform.thatopen.com/documentation).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
Hey @danizep this is a great idea! We are aware of the need to have backend functionality. That's why we have decided to start a new repository for backend components. I believe this solution will allow us to make it much better than just trying to adapt this repository to node. I'm closing this for now, feel free to open issues in that new repository once it's there!
