### ISSUE TITLE
Implement UMD support

### ISSUE THREAD

**Issue by jespa007** [IFCjs/components#16]
Hi,

IFCJs/Components it generates only ESM output. It could be good to create a "Rollup" configuration to implement UMD support.

**Comment by agviegas** [comment]
Hey @jespa007 nice idea! We are aware of the need to execute this in Node.js backends. We have made some tests and adapting this repository to backend might be a bit challenging, and the end result might not be ideal. That's why we have decided to create a new repository called "backend components" (not definitive name) to contain all the functions and logic needed for a backend, including fragment conversion, database, etc. It will also be MIT licensed. It requires more work from our side, but making something specific for backend will probably allow us to go much further. What do you think?

**Comment by jespa007** [comment]
Hi @agviegas .
From my point of view, you have already a well done IFC-Viewer so it's great. For do not mix it up, viewer-backend I would create another repository for exclusively backend_components (for example) that it could be used as an API to perform big processes like generate fragments. IFC.js is already ported in Node.js so I think there's no much more effort that start implementing the backend ;-)
